version: '3.8'

services:
  florella:
    build: .
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    networks:
      - samsebweb_app-network
    restart: unless-stopped

networks:
  samsebweb_app-network:
    external: true
