# Generated by Django 6.0.6 on 2026-06-11 10:49

import tgauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tgauth.models._gen_code, max_length=12, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('tg_name', models.CharField(blank=True, max_length=200)),
                ('tg_username', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram login kodi',
                'verbose_name_plural': 'Telegram login kodlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
