# Generated by Django 6.0.6 on 2026-06-11 13:12

import tgauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlogincode',
            name='code',
            field=models.CharField(default=tgauth.models._gen_code, max_length=64, unique=True),
        ),
    ]
