# Generated by Django 6.0.6 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgauth', '0002_alter_telegramlogincode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ism')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
