# Generated by Django 6.0.6 on 2026-06-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgauth', '0003_telegramcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Masalan: Uy, Ish', max_length=100, verbose_name='Nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (GPS)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (GPS)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='tgauth.telegramcustomer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Mijoz manzili',
                'verbose_name_plural': 'Mijoz manzillari',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
