# Generated by Django 5.2.15 on 2026-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_size_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (S)'),
        ),
    ]
