# Generated by Django 5.2.15 on 2026-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fix_orderitem_price_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqt pul'), ('card', 'Karta')], default='cash', max_length=10, verbose_name="To'lov turi"),
        ),
    ]
