# Generated by Django 5.2.15 on 2026-06-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text="O'chirsangiz xabar yuborilmaydi", verbose_name='Yoqilgan')),
                ('bot_token', models.CharField(blank=True, help_text='@BotFather dan olingan token (123456:ABC-DEF...)', max_length=120, verbose_name='Bot token')),
                ('admin_ids', models.CharField(blank=True, help_text="@userinfobot dan olingan ID. Bir nechta bo'lsa vergul bilan: 111,222. Har bir admin botga avval /start bosishi shart!", max_length=300, verbose_name='Admin ID lar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram sozlamalari',
                'verbose_name_plural': 'Telegram sozlamalari',
            },
        ),
    ]
