# Generated by Django 6.0.6 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_telegramsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
